services:
  - type: web
    name: portfolio
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18
